### ISSUE TITLE
git commands

### ISSUE THREAD

**Issue by junh-ki** [junh-ki/elasticsearch#4]
git log
git branch

git fetch origin
git reset --hard origin/master

git merge --squash feature
git commit -m "feature branch merged"

git checkout feature
git rebase main // Successfully rebased and updated refs/heads/feature.
git push

git stash
git stash clear

git stash
git stash apply stash

**Comment by junh-ki** [comment]
squashing and rebasing


squash

command + shift + K (you can see your changes)

force push

rebase

force push

**Comment by junh-ki** [comment]
[VIS-94] entire property tag added to help users find covid safe properties 
git left cornor

**Comment by Nappy-Says** [comment]
@junh-ki 
Hey, junh, hi
I'm sorry, can you help me with merge?

**Comment by junh-ki** [comment]
> @junh-ki
> Hey, junh, hi
> I'm sorry, can you help me with merge?

Hi, what merge u want me to help you with?
